[build]
  # Directory with the build files
  base = "frontend"
  
  # Directory that contains the deploy-ready HTML files and assets
  publish = "frontend/build"
  
  # Build command
  command = "npm run build"

# Redirect all requests to index.html for React Router to handle
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
